name: React TypeScript PWA Expense Tracker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      # Deploy para o Surge.sh (caso esteja usando o Surge)
      - name: Install Surge
        run: npm install -g surge
      - name: Deploy to Surge
        run: surge ./build react-ts-pwa-expense-tracker.surge.sh --token ${{secrets.FIREBASE_TOKEN}}

      # Deploy para o Firebase (caso esteja usando Firebase Hosting)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --token ${{secrets.FIREBASE_TOKEN}}
